trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo Build FirstJob
          - bash: echo ${PipelineVariable}
      - job: SecondJob
        steps:
          - bash: echo Build SecondJob

  - stage: DevDeploy
    dependsOn: Build # dzięki temu możemy zrównoleglić pracę stagy w danych sytuacjach
    jobs:
      - job: DevDeployJob
        steps:
          - bash: echo DevDeployJob

  - stage: QADeploy
    dependsOn: Build # nie musi czekać na wykonanie stage'a DevDeploy
    jobs:
      - job: QADeployJob
        steps:
          - bash: echo QADeployJob

  - stage: ProdDeploy
    dependsOn: # musi poczekać aż stage QADeploy i DevDeploy zostaną zakończone
      - QADeploy
      - DevDeploy
    jobs:
      - job: ProdDeployJob
        steps:
          - bash: echo ProdDeployJob
