trigger:
- main

resources:
  - repo: self # te z którego korzystamy

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Stage1
    jobs:
      - job: FirstJob
        steps:
          - bash: ls $(System.DefaultWorkingDirectory)
  - stage: Stage2
    jobs:
      - job: SecJob
        steps:
          - bash: ls $(System.DefaultWorkingDirectory)

  # - stage: Stage2
  #   jobs:
  #     - job: QADeployJob

